force-app/main/default/objects/Cloudinary_Master_Settings__c/Cloudinary_Master_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Cloudinary Master Settings</label>
</CustomObject>

force-app/main/default/objects/Cloudinary_Master_Settings__c/fields/API_Key__c.field-meta.xml
<CustomField>
    <fullName>API_Key__c</fullName>
    <label>API_Key</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cloudinary_Master_Settings__c/fields/API_Secret__c.field-meta.xml
<CustomField>
    <fullName>API_Secret__c</fullName>
    <label>API_Secret</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cloudinary_Master_Settings__c/fields/Cloud_Name__c.field-meta.xml
<CustomField>
    <fullName>Cloud_Name__c</fullName>
    <label>Cloud_Name</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cloudinary_Master_Settings__c/fields/End_Point__c.field-meta.xml
<CustomField>
    <fullName>End_Point__c</fullName>
    <label>End_Point</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Cloudinary_RequestBuilder.cls
public class Cloudinary_RequestBuilder {
    
    //Method to build request 
    public static HttpRequest buildRequest(String endpointName, String methodType, String body) {
        Cloudinary_Master_Settings__c cloudinarySettings = Cloudinary_Master_Settings__c.getOrgDefaults();
        String endPoint = cloudinarySettings.End_Point__c + cloudinarySettings.Cloud_Name__c + Cloudinary_Queries.getMehodNameByName(endpointName);
        HttpRequest req = new HttpRequest();
        req.setEndpoint(endPoint);
        req.setMethod(methodType);
        if(methodType == 'DELETE') {
            String username = cloudinarySettings.API_Key__c;
            String password = cloudinarySettings.API_Secret__c;
            Blob headerValue = Blob.valueOf(username + ':' + password);
            String authorizationHeader = 'BASIC ' +EncodingUtil.base64Encode(headerValue);
            req.setHeader('Authorization', authorizationHeader); 
        }
        req.setHeader('Content-Type', 'application/json');
        if (body != null) {
            req.setBody(body);
        }
        return req;
    }
    
    public static HttpRequest uploadResource(ContentVersion conVer) {
        //Call the buildRequest method to generate the HttpRequest object
        return buildRequest(
            Cloudinary_Constants.ENDPOINT_DEVELOPER_NAME_UPLAOD_IMAGE_API,
            Cloudinary_Constants.METHOD_TYPE_POST,
            Cloudinary_JSONBodyBuilder.createJSON(conVer)
        );
    }
    
    public static HttpRequest downloadResource(ContentVersion conVer,Cloudinary_Wrapper responseFile) {
        HttpRequest imageRequest = new HttpRequest();
        imageRequest.setEndpoint(responseFile.secure_url);
        System.debug('responseFile.secure_url--->'+responseFile.secure_url);
        imageRequest.setMethod('GET'); 
        return imageRequest;
    }
    
    public static HttpRequest deleteResource(List<String> publicIds) {
       return buildRequest(
            Cloudinary_Constants.ENDPOINT_DEVELOPER_NAME_RESOURCE_API,
            Cloudinary_Constants.METHOD_TYPE_DELETE,
            Cloudinary_JSONBodyBuilder.createJSONForDeleteResource(publicIds)
        );
    }
}